export const SET_PRODUCT_CATEGORY = 'SET_PRODUCT_CATEGORY';
export const SET_PRODUCT_NAME = 'SET_PRODUCT_NAME';
export const SET_PRODUCT_REFERENCE =
  'SET_PRODUCT_REFERENCE';
export const SET_PRODUCT_DESCRIPTION =
  'SET_PRODUCT_DESCRIPTION';
